# Define a global platform for your project
platform :ios, '15.0'

target 'MayaExam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MayaExam
  pod 'Moya', '~> 15.0'
  pod 'Moya/Combine', '~> 15.0'
  pod 'SnapKit', '~> 5.7'

  target 'MayaExamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MayaExamUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  # Xcode's "User Script Sandboxing" can break CocoaPods' embed frameworks script
  # in constrained environments. Disable it for pods + the user project.
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |native_target|
      native_target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    aggregate_target.user_project.save
  end
end
